export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_FEATURED_PRODUCTS = 'SET_FEATURED_PRODUCTS';

export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const SET_PRODUCTS_LOADING = 'SET_PRODUCTS_LOADING';
export const GET_PRODUCTS_LOADING = 'GET_PRODUCTS_LOADING'; //for the filter context
export const SET_UNIQUE_TYPES = 'SET_UNIQUE_TYPES';
export const CHANGE_FILTERED_PRODUCTS = 'CHANGE FILTERED_PRODUCTS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const INCREASE_ITEM_COUNT = 'INCREASE_ITEM_COUNT';
export const DECREASE_ITEM_COUNT = 'DECREASE_ITEM_COUNT';
export const COUNT_TOTAL_NUM_CART_ITEMS = 'COUNT_TOTAL_NUM_CART_ITEMS';
export const COUNT_TOTAL_AMOUNT_ALL_ITEMS = 'COUNT_TOTAL_AMOUNT_ALL_ITEMS';

export const SET_NEXT_PAGE = 'SET_NEXT_PAGE';
export const SET_PREV_PAGE = 'SET_PREV_PAGE';
